### ISSUE TITLE
下载项目之后运行不起来

### ISSUE THREAD

**Issue by zhangjiang1203** [Sky24n/flutter_wanandroid#105] opened 2020-05-25 11:03 UTC
clone之后运行flutter packages get成功，run直接失败

Compiler message:
lib/common/component_index.dart:8:1: Error: 'VersionModel' is exported from both 'package:flutter_wanandroid/models/models.dart' and 'package:base_library/src/models/model.dart'.
export 'package:base_library/base_library.dart';
^
lib/demos/date_page.dart:16:3: Error: Type 'DateFormat' not found.
  DateFormat _dateFormat = DateFormat.NORMAL;
  ^^^^^^^^^^
lib/demos/date_page.dart:22:19: Error: Type 'DateFormat' not found.
  void inputCheck(DateFormat format) {
                  ^^^^^^^^^^
lib/demos/timeline_page.dart:15:7: Error: The non-abstract class 'ZHAliPayTimelineInfo' is missing implementations for these members:
 - TimelineInfo.lessThanOneMinute
 - TimelineInfo.maxJustNowSecond
 - TimelineInfo.weeks
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ZHAliPayTimelineInfo implements TimelineInfo {
      ^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-1.2.0/lib/src/timeline_util.dart:37:10: Context: 'TimelineInfo.lessThanOneMinute' is 

我这边的运行环境
 flutter_wanandroid   master ●  flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/zj/flutter
    • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zj/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/zj/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/zj/Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    •  • ios • iOS 13.4.1

**Comment by Sky24n** [comment] 2020-05-25 13:05
Duplicate of #104

**Comment by Sky24n** [comment] 2020-05-27 03:32
先把那个文件的代码屏蔽了吧

**Comment by Sky24n** [comment] 2020-05-29 15:46
fix

**Closed** 2020-05-30 12:56 UTC

**Comment by zhangjiang1203** [comment] 2020-06-02 03:48
对应的文件没有上传？

**Comment by Sky24n** [comment] 2020-06-02 04:10
一眼就能看出来，库升级了，代码还是旧版引起的不兼容！
