### ISSUE TITLE
Error: Method not found: 'ImageStreamListener'.

### ISSUE THREAD

**Issue by laixiangcao** [Sky24n/flutter_wanandroid#60] opened 2019-06-02 05:53 UTC
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
file:///Users/jiumeng/Documents/Flutter/flutter_sdk/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5+1/lib/src/widget_util.dart:86:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/jiumeng/Documents/Flutter/flutter_sdk/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5+1/lib/src/widget_util.dart:86:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
file:///Users/jiumeng/Documents/Flutter/flutter_sdk/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5+1/lib/src/widget_util.dart:117:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/jiumeng/Documents/Flutter/flutter_sdk/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5+1/lib/src/widget_util.dart:117:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
Compiler failed on /Users/jiumeng/Documents/Flutter/flutter_wanandroid/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/jiumeng/Documents/Flutter/flutter_sdk/packages/flutter_tools/gradle/flutter.gradle' line: 529

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/Users/jiumeng/Documents/Flutter/flutter_sdk/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sky24n** [comment] 2019-06-03 02:19
Duplicate of #[10](https://github.com/Sky24n/flustars/issues/10)

**Closed** 2019-07-09 02:53 UTC
