### ISSUE TITLE
运行不起来 

### ISSUE THREAD

**Issue by co3318co** [Sky24n/flutter_wanandroid#106] opened 2020-05-27 03:06 UTC
(This is taking an unexpectedly long time.)⣾
Compiler message:
lib/demos/date_page.dart:16:3: Error: Type 'DateFormat' not found.
  DateFormat _dateFormat = DateFormat.NORMAL;
  ^^^^^^^^^^
(This is taking an unexpectedly long time.)⣽lib/demos/date_page.dart:22:19: Error: Type 'DateFormat' not found.
  void inputCheck(DateFormat format) {
                  ^^^^^^^^^^
(This is taking an unexpectedly long time.)⣽lib/demos/timeline_page.dart:15:7: Error: The non-abstract class 'ZHAliPayTimelineInfo' is
missing implementations for these members:
 - TimelineInfo.lessThanOneMinute
 - TimelineInfo.maxJustNowSecond
 - TimelineInfo.weeks
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ZHAliPayTimelineInfo implements TimelineInfo {
      ^^^^^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:37:10: Context: 'TimelineInfo.lessThanOneMinute' is defined
here.
  String lessThanOneMinute() => ''; //just now(刚刚).
         ^^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:35:7: Context: 'TimelineInfo.maxJustNowSecond' is defined here.
  int maxJustNowSecond() => 30; // max just now second.
      ^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:55:10: Context: 'TimelineInfo.weeks' is defined here.
  String weeks(int week) => ''; //x week(星期x).
         ^^^^^
lib/demos/timeline_page.dart:43:7: Error: The non-abstract class 'ENAliPayTimelineInfo' is
missing implementations for these members:
 - TimelineInfo.lessThanOneMinute
 - TimelineInfo.maxJustNowSecond
 - TimelineInfo.weeks
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ENAliPayTimelineInfo implements TimelineInfo {
      ^^^^^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:37:10: Context: 'TimelineInfo.lessThanOneMinute' is defined
here.
  String lessThanOneMinute() => ''; //just now(刚刚).
         ^^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:35:7: Context: 'TimelineInfo.maxJustNowSecond' is defined here.
  int maxJustNowSecond() => 30; // max just now second.
      ^^^^^^^^^^^^^^^^
../../Downloads/myflutterpath/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-1.2.0
/lib/src/timeline_util.dart:55:10: Context: 'TimelineInfo.weeks' is defined here.
  String weeks(int week) => ''; //x week(星期x).
         ^^^^^
Upgrading project.pbxproj                   
Legacy build system detected, removing
/Users/apple/Desktop/flutter_wanandroid-master/ios/Runner.xcworkspace/xcshareddata/Workspace
Settings.xcsettings
lib/demos/date_page.dart:16:3: Error: 'DateFormat' isn't a type.        
  DateFormat _dateFormat = DateFormat.NORMAL;                           
  ^^^^^^^^^^                                                            
lib/demos/date_page.dart:16:28: Error: Getter not found: 'DateFormat'.  
  DateFormat _dateFormat = DateFormat.NORMAL;                           
                           ^^^^^^^^^^                                   
lib/demos/date_page.dart:22:19: Error: 'DateFormat' isn't a type.       
  void inputCheck(DateFormat format) {                                  
                  ^^^^^^^^^^                                            
lib/demos/date_page.dart:25:20: Error: Method not found: 'DateUtil.getDateStrByMs'.
          DateUtil.getDateStrByMs(                                      
                   ^^^^^^^^^^^^^^                                       
lib/demos/date_page.dart:29:20: Error: Method not found: 'DateUtil.getWeekDay'.
          DateUtil.getWeekDay(DateTime.now()) +                         
                   ^^^^^^^^^^                                           
lib/demos/date_page.dart:31:20: Error: Method not found: 'DateUtil.getZHWeekDay'.
          DateUtil.getZHWeekDay(DateTime.now());                        
                   ^^^^^^^^^^^^                                         
lib/demos/date_page.dart:38:23: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
    inputCheck(isZH ? DateFormat.ZH_NORMAL : DateFormat.NORMAL);        
                      ^^^^^^^^^^                                        
lib/demos/date_page.dart:38:46: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
    inputCheck(isZH ? DateFormat.ZH_NORMAL : DateFormat.NORMAL);        
                                             ^^^^^^^^^^                 
lib/demos/date_page.dart:86:54: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                              value: (_dateFormat == DateFormat.DEFAULT),
                                                     ^^^^^^^^^^         
lib/demos/date_page.dart:90:51: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                                    _dateFormat = DateFormat.DEFAULT;   
                                                  ^^^^^^^^^^            
lib/demos/date_page.dart:92:43: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                                        ? DateFormat.ZH_DEFAULT         
                                          ^^^^^^^^^^                    
lib/demos/date_page.dart:109:54: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                              value: (_dateFormat == DateFormat.NORMAL),
                                                     ^^^^^^^^^^         
lib/demos/date_page.dart:113:51: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                                    _dateFormat = DateFormat.NORMAL;    
                                                  ^^^^^^^^^^            
lib/demos/date_page.dart:115:43: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                                        ? DateFormat.ZH_NORMAL          
                                          ^^^^^^^^^^                    
lib/demos/date_page.dart:133:35: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'DateFormat'.
                                  DateFormat.YEAR_MONTH_DAY_HOUR_MINUTE),
                                  ^^^^^^^^^^                            
lib/demos/date_page.dart:138:41: Error: The getter 'DateFormat' isn't defined for the class
'_DatePageState'.
 - '_DatePageState' is from 'package:flutter_wanandroid/demos/date_page.dart'
 ('lib/demos/date_page.dart').

很多下载这个项目的都是新手 说一下配置环境吧 别的开源项目都能打开

**Comment by Sky24n** [comment] 2020-05-27 03:29
Duplicate of #105

**Comment by Sky24n** [comment] 2020-05-29 15:45
fix

**Closed** 2020-05-30 12:56 UTC
